/**
 * Supabase schema types, in the shape generated by `supabase gen types`.
 *
 * These are hand-maintained to mirror the intended remote schema (the TDD's
 * tables). Column names are snake_case because that is how they are stored in
 * Postgres/Supabase. Domain-facing camelCase types live in `types/board.ts`,
 * `types/completion.ts` and `types/widgetConfig.ts`.
 */

export type BoardRow = {
  id: string;
  user_id: string;
  name: string;
  icon: string;
  color: string;
  layout: 'heatmap' | 'pill' | 'ring';
  track_amounts: boolean;
  unit: string;
  use_default_amount: boolean;
  default_amount: number | null;
  daily_target_amount: number | null;
  allow_exceeding: boolean;
  reminder_enabled: boolean;
  reminder_time: string | null;
  archived: boolean;
  created_at: string;
  updated_at: string;
};

export type BoardInsert = {
  id?: string;
  user_id: string;
  name: string;
  icon: string;
  color: string;
  layout?: 'heatmap' | 'pill' | 'ring';
  track_amounts?: boolean;
  unit?: string;
  use_default_amount?: boolean;
  default_amount?: number | null;
  daily_target_amount?: number | null;
  allow_exceeding?: boolean;
  reminder_enabled?: boolean;
  reminder_time?: string | null;
  archived?: boolean;
  created_at?: string;
  updated_at?: string;
};

export type BoardUpdate = Partial<BoardRow>;

export type CompletionRow = {
  id: string;
  board_id: string;
  completed_on: string;
  note: string | null;
  created_at: string;
  updated_at: string;
};

export type CompletionInsert = {
  id?: string;
  board_id: string;
  completed_on: string;
  note?: string | null;
  created_at?: string;
  updated_at?: string;
};

export type CompletionUpdate = Partial<CompletionRow>;

export type WidgetConfigRow = {
  id: string;
  user_id: string;
  board_id: string | null;
  scope: 'home' | 'board';
  widget_type: string;
  position: number;
  created_at: string;
  updated_at: string;
};

export type WidgetConfigInsert = {
  id?: string;
  user_id: string;
  board_id?: string | null;
  scope: 'home' | 'board';
  widget_type: string;
  position?: number;
  created_at?: string;
  updated_at?: string;
};

export type WidgetConfigUpdate = Partial<WidgetConfigRow>;

export type ProfileRow = {
  user_id: string;
  username: string;
  created_at: string;
  updated_at: string;
};

export type ProfileInsert = {
  user_id: string;
  username: string;
  created_at?: string;
  updated_at?: string;
};

export type ProfileUpdate = Partial<ProfileRow>;

export type Database = {
  public: {
    Tables: {
      boards: {
        Row: BoardRow;
        Insert: BoardInsert;
        Update: BoardUpdate;
        Relationships: [];
      };
      completions: {
        Row: CompletionRow;
        Insert: CompletionInsert;
        Update: CompletionUpdate;
        Relationships: [];
      };
      widget_configs: {
        Row: WidgetConfigRow;
        Insert: WidgetConfigInsert;
        Update: WidgetConfigUpdate;
        Relationships: [];
      };
      profiles: {
        Row: ProfileRow;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      is_email_registered: {
        Args: { target: string };
        Returns: boolean;
      };
    };
  };
}
